### ISSUE TITLE
deploy argocd to quicklab

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#11]
Create an implementation specific fork of https://github.com/operate-first/cd to target quicklab clusters

**Comment by tumido** [comment]
This was simple! :slightly_smiling_face: 

1. kube:admin is not supported in user api, therefore user has to create additional user. Simplest way is to deploy an Oauth via Htpasswd:

  1. Create a htpasswd config file and deploy it to OpenShift: 
```
$ htpasswd -nb username password > oc.htpasswd
$ oc create secret generic htpass-secret --from-file=htpasswd=oc.htpasswd -n openshift-config
$ cat <<EOF | oc apply -f - 
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
EOF
```
  2. Grant the new user admin cluster-admin rights
```
oc adm policy add-cluster-role-to-user cluster-admin username
```
2. Now log out and log in using the htpasswd provider. Generate new API token and login via this token on your local CLI

The dev environment then can be deployed without any changes to the sources, since the user is cluster admin on it's Quicklab cluster:

```
$ kustomize build manifests/crds --enable_alpha_plugins | oc apply -f -
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
clusterrole.rbac.authorization.k8s.io/argocd-events-create-aggregate-to-admin created
clusterrole.rbac.authorization.k8s.io/argocd-proj-apps-aggregate-to-admin created

$ kustomize build manifests/overlays/dev --enable_alpha_plugins | oc apply -f -
serviceaccount/argocd-application-controller created
serviceaccount/argocd-dex-server created
serviceaccount/argocd-manager created
serviceaccount/argocd-server created
role.rbac.authorization.k8s.io/argocd-application-controller created
role.rbac.authorization.k8s.io/argocd-dex-server created
role.rbac.authorization.k8s.io/argocd-server created
clusterrole.rbac.authorization.k8s.io/argocd-manager-role created
rolebinding.rbac.authorization.k8s.io/argocd-application-controller created
rolebinding.rbac.authorization.k8s.io/argocd-dex-server created
rolebinding.rbac.authorization.k8s.io/argocd-server created
clusterrolebinding.rbac.authorization.k8s.io/argocd-manager-role-binding created
configmap/argocd-cm created
configmap/argocd-rbac-cm created
configmap/argocd-ssh-known-hosts-cm created
configmap/argocd-tls-certs-cm created
secret/argocd-dex-server-oauth-token created
secret/argocd-secret created
secret/dev-cluster-spec created
secret/ksops-pgp-key created
service/argocd-dex-server created
service/argocd-metrics created
service/argocd-redis created
service/argocd-repo-server created
service/argocd-server created
service/argocd-server-metrics created
deployment.apps/argocd-application-controller created
deployment.apps/argocd-dex-server created
deployment.apps/argocd-redis created
deployment.apps/argocd-repo-server created
deployment.apps/argocd-server created
appproject.argoproj.io/dev created
application.argoproj.io/dev-app created
route.route.openshift.io/argocd-metrics created
route.route.openshift.io/argocd-server created
route.route.openshift.io/argocd-server-metrics created

$ examples/configure_development.sh
serviceaccount/argocd-dex-server patched
secret/argocd-secret patched
configmap/argocd-cm replaced
secret/dev-cluster-spec patched
secret/dev-cluster-spec patched
application.argoproj.io/dev-app replaced
group.user.openshift.io/dev-group created
group.user.openshift.io/dev-group added: "username"
```

**Comment by durandom** [comment]
@tumido do you have some screenshots of the cluster type to be requested? There's a myriad of options

**Comment by tumido** [comment]
yes, I can create a guide for that as well. :)

**Comment by tumido** [comment]
Set up a proper quicklab cluster:
1) Go to https://quicklab.upshift.redhat.com/ and log in (top right corner)
2) Click **New cluster**
3) Select **openshift4upi** template and a region you like the most, then select the reservation duration, the rest can be left as is:
![image](https://user-images.githubusercontent.com/7453394/93217088-d75bd280-f768-11ea-8051-8bb1b9eb7fd1.png)
4) Go to cluster page by clicking on the cluster name in **My clusters** table
5) Once the cluster reaches **Active** state your cluster history should look like this:
![image](https://user-images.githubusercontent.com/7453394/93218936-15f28c80-f76b-11ea-94e2-d4dd36d94bcc.png)
6) Now click on **New Bundle** button in **Product information** section
7) Select **openshift4upi** bundle. A new form loads - you can keep all the values as they are (you can ignore the warning on top as well, since this is the first install attempt of Openshift on that cluster):
![image](https://user-images.githubusercontent.com/7453394/93219556-c6f92700-f76b-11ea-8adb-c661e6ad4a75.png)
8) Wait for OCP4 to install. After successful installation you should see a clsuter history log like this:
![image](https://user-images.githubusercontent.com/7453394/93236330-fd8c6d00-f77e-11ea-94b7-f75dc254fbf9.png)
9) Use the link and credentials from the **Cluster Information** section to access your cluster.
![image](https://user-images.githubusercontent.com/7453394/93236592-4e03ca80-f77f-11ea-8a10-883518990b14.png)
10) Follow the guide above https://github.com/operate-first/continuous-deployment/issues/11#issuecomment-689599451
