### ISSUE TITLE
cd target to crc

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#2]
Create an implementation specific fork of https://github.com/operate-first/cd to target https://code-ready.github.io/crc/

**Comment by anishasthana** [comment]
Is the aim of this a minimal deployment of ODH that can run on a minimal crc instance?

**Comment by anishasthana** [comment]
Clarified offline -- this is to deploy ArgoCD.

**Comment by anishasthana** [comment]
Does it _need_ to be a fork? Could we just use overlays instead?

**Comment by HumairAK** [comment]
I think this task should be reduced to just writing docs on how to do it, and the one handling it should do local testing of a fork setup etc.  

Suggestion that the outcome of this should be: 
Include documentations on how one can fork and setup their own continous-deployment fork (or use the base provided by this repo). Then we can use these docs to setup the implementation specific fork/repo for the MOC deployment. 

Reason: 
The context here is because **first time** deployment of argocd on a **new** cluster requires a multi-step process. Roughly the steps translate to: 
- Fork this repo 
- Deploy from the manifests in this fork -- some stuff won't work like openshift auth
- Retrieve the routes for argocd api server, your specific cluster's api server, oauth client token, etc. 
- Update auth configuration manifests with this retrieved info, and store these in vcs, deploy 
- Auth working 

Because a local crc deployment is for intents and purposes an ephemeral deployment, and can change, I don't think it makes sense to have this information on vcs. IMHO this makes more sense for living non-changing clusters, where the routes will stay consistent.

**Comment by durandom** [comment]
Since your first step is "Fork this repo", let's do this and see where the all the implementation specific stuff lives. We can discuss this in PRs then.

* Fork this repo
* Add manual documentation in the first PR to the fork
* Add implementation specifics (routes, secrets, IPs) in a 2nd PR and discuss where it should go. (Probably generated from a script? Like `crc status`)

**Comment by martinpovolny** [comment]
* Follow steps in https://github.com/operate-first/operate-first.github.io/issues/1#issuecomment-688661247
* Argo CD will be running at: https://argocd-server-aicoe-argocd-dev.apps-crc.testing/

TODO: authentication, example app

**Comment by martinpovolny** [comment]
I forked the repo here: https://github.com/martinpovolny/continuous-deployment-crc/
Once there's actually anything I'll move it under the org

**Comment by tumido** [comment]
FYI: you will probably encounter the same issue as I did here https://github.com/operate-first/continuous-deployment/issues/11#issuecomment-689599451 `kube:admin` is not supposed to be used with user api. Just create another user as described in the linked comment. :slightly_smiling_face:

**Comment by martinpovolny** [comment]
> FYI: you will probably encounter the same issue as I did here [#11 (comment)](https://github.com/operate-first/continuous-deployment/issues/11#issuecomment-689599451) `kube:admin` is not supposed to be used with user api. Just create another user as described in the linked comment.

Yes, I did, we discussed in the public channel.

**Comment by tumido** [comment]
😀 too many messages to keep track of... 👍

**Comment by martinpovolny** [comment]
I have added more detailed steps and changes here:
https://github.com/martinpovolny/continuous-deployment-crc

To close the issue, @hemajv : can you, please, try if these steps work for you, suggest changes/whatever and when you are happy we move the repo under this org?

@tumido : would you care to take a look too?

**Comment by martinpovolny** [comment]
resolved by https://github.com/operate-first/continuous-deployment/pull/33
