### ISSUE TITLE
ArgoCD Apps of Apps architecture proposal

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#68]
ArgoCD is live on MOC and we have created the appropriate projects/permissions to start deploying applications. 

Before we do that I think we should have a brief discussion on how we should set up our applications on argocd declaratively. 

**For Context:** 
ArgoCD [Applications](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#applications) manifests are a declarative way to manage Argocd applications in git. Traditiionaly we've stored these alongside argocd deployment manifests, like IDH has done [here](https://github.com/AICoE/aicoe-cd/tree/master/manifests/overlays/prod/applications).

This has been fine in the past since we controlled the deployment of ArgoCD and had merge access to the repo where the applications were stored. So if we wanted to onboard a new app, we make a PR with the application manifest and someone on our team would merge it (see [this pr](https://github.com/AICoE/aicoe-cd/pull/133/files) as an example).

But now we have a situation where MOC manages Argocd [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/tree/master/manifests/argocd). It was added to this repo because it's a cluster-wide argocd that can be used to manage cluster resources as well.

**The Problem:** 
If we applied our current practice, we'd store our app manifests [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/tree/master/manifests/argocd/overlays/prod/applications). The problem is that _we_ don't have merge access to this repo, and it wouldn't really make much sense for people who manage the infrastructure to also handle PR's that don't pertain directly to cluster management.

**Proposed Solution**
To reconcile this dilemma I'd like to put forth the following suggestion in how we can organize our repository/argocd applications: 

![image](https://user-images.githubusercontent.com/10904967/99705533-d8aac380-2a67-11eb-88e9-b63582271994.png)

The `Infra Repo` is analogous to the `moc-cnv-sandbox` repo here, but could be replaced with another repo as well. 

The idea here is that all our operate-first/thoth/data-science Argocd Applications would go in the `opf-argocd-apps` repo. Then we'd have an App of Apps i.e. the `OPF Parent App` that manages all these apps. This way we can add new applications declaratively to ArgoCD w/o having to make PR's to the `Infra Repo` (or `moc-cnv-sandbox`). Operate-first admins would manage the `opf-argocd-app` repo. Any other argocd applications that manage cluster resources like `clusterrolebindings` or operator `subscriptions` etc. can remain in the infra repo since that's a concern for cluster admins. We would direct any _user_ of moc that wants to use ArgoCD to manage their apps to add their ArgoCD apps to the `opf-argocd-apps` repo. 

Pros: 
- MOC Admins/Ops are not bombarded with PR's for ArgoCD App onboarding 
- OperateFirst maintainers can handle the PR's unhindered 
- The "OPF-ArgoCD-Apps" repo can be leveraged by CRC/Quicklab/Other OCP Clusters to quickly setup ArgoCD ODH/Thoth/etc. Applications. 

Cons: 
One concern here is that there is no way to automatically enforce that Applications in `opf-argocd-apps` repo _belong_ to the `Operate First` argocd project (see diagaram). _Why is this a problem?_ Because we use ArgoCD projects to restrict what types of resources applications _in that project can deploy_. For example argocd apps in the `Infra Apps` project in the diagram can deploy `clusterrolebinding`, `operators`, etc. So while `OPF Parent App` cannot deploy `clusterrolebindings` because it belongs to the `Operate First` argocd project, it could deploy another ArgoCD application that belongs to `Infra apps` and _that argocd app_ could deploy clusterrolebindings`. 

You can read more about this [issue here](https://github.com/argoproj/argo-cd/issues/3045). The individual there used admission hooks to get around this but I don't think we want to go there just yet. My suggestion is we begin by enforcing this at the PR level, and transition to maybe catching this in CI until there's a proper solution upstream.

**Comment by anishasthana** [comment]
This lines up with what we're doing for internal data hub too, I like it.

**Comment by 4n4nd** [comment]
I like the proposed solution as it keeps all the control to our repos.

**Comment by durandom** [comment]
cc  @larsks

**Comment by durandom** [comment]
@HumairAK great writeup. I don't see any issues with this and it sounds like a good practice. 

Can you start re-phrasing it in a more generic way and have MOC and ODH just as an example and create a PR to https://github.com/operate-first/blueprint

**Comment by HumairAK** [comment]
@durandom  added a PR https://github.com/operate-first/blueprint/pull/6

**Comment by larsks** [comment]
@HumairAK that all seems like a fine way to structure things. I agree that we can live with the issue you highlighted for now; our set of users right now is relatively trusted.

Regarding the linked argocd issue, I see that yesterday it was added to a development milestone.

**Comment by HumairAK** [comment]
@larsks  yes I noticed that as well -- once it arrives in ArgoCD v1.9 (right now the next major release is 1.8) we'll be able to allow other teams to create / manage their own argocd applications in their respective repos without having to worry about whether they can create those applications under a restricted project.

**Comment by tumido** [comment]
I like this proposal since it's very logically structured.

I have one big concern though, which seems to me that will break the backbone of this. We'd like to deploy ODH using this scheme, right? ODH is a mix of different components:
1. Some of them are namespace resource manifests only (e.g. [superset](https://github.com/opendatahub-io/odh-manifests/tree/master/superset/base))
2. Some of them contain CRDs and cluster roles for those CRDs (e.g. [argo](https://github.com/opendatahub-io/odh-manifests/tree/master/odhargo/cluster/base))
3. Some are namespaced operators (e.g. [spark](https://github.com/opendatahub-io/odh-manifests/tree/master/radanalyticsio/spark/cluster/base))
4. And some are cluster wide operators (e.g. [kafka](https://github.com/opendatahub-io/odh-manifests/tree/master/kafka/cluster/base))

This proposal suggests that applications changing "cluster wide" resources should be hosted in the `infra` repo, while the applications which are strictly namespace scoped, would go under `opf-argocd-apps`. That would mean effectively splitting ODH Applications into multiple repositories anyways.

There are also some ODH components like `argo` which has multiple sub-components deployed separately ([see here](https://github.com/opendatahub-io/odh-manifests/blob/e659018664c85cff9d206122bb709cafabb72291/tests/setup/kfctl_openshift.yaml#L90-L99)) - one cluster-wide part, and another namespace scoped sub-component. This proposal would split this single argo "parent component" into 2 applications in 2 different repos.

Another aspect to this story is that ODH upstream has a preference of maintaining a single `kfdef` resource on a cluster, and do the namespacing within the `kfdef` resource (as discussed in https://github.com/opendatahub-io/odh-manifests/issues/236). This won't play nicely with multiple ArgoCD apps anyways. We (Vasek and me) have some consecutive proposals to that to allow cross namespace sync for namespaced installs, but that has to be consulted with kubeflow upstream first, so don't care about that much for now.

**Comment by HumairAK** [comment]
@tumido  -- really good points! I think we have to make an exception for ODH here because it's a meta operator. But since the _kfdef_ itself is a namespace resource, I think it's fine to store that alongside the `opf-argocd-app` repo, but keep the subscriptions for the operator in the `infra` repo (like [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/tree/master/manifests/operators/odh)). 

> this won't play nicely with multiple ArgoCD apps anyways.

I'm not sure if I see the problem, can you elaborate? When it all becomes one kfdef, we'll keep one argocd ODH app for one kfdef, since we're not there yet we'll keep multiple apps. The idea is to expand on to other apps aside from odh as well in the future.

**Comment by durandom** [comment]
@tumido I think your already anticipating the problems that we'll face, which is good :) 

Let's get https://github.com/operate-first/blueprint/pull/6 in and see into which problems we run. Then we have it all documented.

**Comment by HumairAK** [comment]
Closing this issue since I think we're all agreed here. Feel free to re-open if there's more to discuss.
